#!/bin/bash

if [ "$#" != "1" ]; then
    echo "You need to provide a single argument."
    exit 1
fi

HMMFILE="/app/data/$1"
if ! test -f "$HMMFILE"; then
    echo "$HMMFILE does not exist."
    exit 1
fi

echo -n "Pressing $HMMFILE... "
/app/bin/hmmpress "$HMMFILE" >/app/logs/h3press.log 2>&1 || exit 1
echo "done."

h3master_pid=0
h3worker_pid=0

term_handler() {
    if [ "$h3worker_pid" -ne 0 ]; then
        kill -SIGTERM "$h3worker_pid"
        wait "$h3worker_pid"
    fi
    if [ "$h3master_pid" -ne 0 ]; then
        kill -SIGTERM "$h3master_pid"
        wait "$h3master_pid"
    fi
    exit 143 # 128 + 15 -- SIGTERM
}
trap 'kill ${!}; term_handler' SIGTERM

/app/bin/hmmpgmd --master --hmmdb "$HMMFILE" >/app/logs/h3master.log 2>&1 &
h3master_pid="$!"

/app/bin/hmmpgmd --worker 127.0.0.1 >/app/logs/h3worker.log 2>&1 &
h3worker_pid="$!"

# wait forever
while true; do
    # tail -f /dev/null &
    tail -f /app/logs/h3master.log &
    wait ${!}
done
