#!/bin/bash

early_term_handler() {
    exit 0
}
trap 'early_term_handler' SIGINT
trap 'early_term_handler' SIGTERM

if [ "$#" != "1" ]; then
    echo >&2 "You need to provide a single argument."
    exit 1
fi

HMMFILE="/app/data/$1"
if ! test -f "$HMMFILE"; then
    echo >&2 "$HMMFILE does not exist."
    exit 1
fi

echo -n "Pressing $HMMFILE... " | tee /app/logs/h3press.log
if { /app/bin/hmmpress "$HMMFILE"; } >>/app/logs/h3press.log 2>&1; then
    echo "done." | tee -a /app/logs/h3press.log
else
    echo >&2 "Failed to press file $HMMFILE."
    echo "failed." | tee -a /app/logs/h3press.log
    exit 1
fi

h3master_pid=0
h3worker_pid=0

term_handler() {
    local exit_code=0

    /usr/bin/nc 127.0.0.1 51371 <<EOF
!shutdown
//
EOF

    if [ "$h3worker_pid" -ne 0 ]; then
        if ! wait "$h3worker_pid"; then
            exit_code=1
        fi
    fi

    if [ "$h3master_pid" -ne 0 ]; then
        if ! wait "$h3master_pid"; then
            exit_code=1
        fi
    fi

    exit $exit_code
}
trap 'kill ${!}; term_handler' SIGINT
trap 'kill ${!}; term_handler' SIGTERM

/app/bin/hmmpgmd --master --hmmdb "$HMMFILE" >/app/logs/h3master.log 2>&1 &
h3master_pid="$!"

/app/bin/hmmpgmd --worker 127.0.0.1 >/app/logs/h3worker.log 2>&1 &
h3worker_pid="$!"

# wait forever
while true; do
    tail -f /app/logs/h3master.log &
    wait ${!}
done
