name: Test
on: push

jobs:
  test:
    name: Test when ${{ matrix.test_when }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        test_when: [working, failing]

    steps:
      - uses: actions/checkout@v2

      - name: Install 7-Zip
        run: sudo apt-get install 7zip

      - name: Download minifam.hmm.7z
        run: curl -O https://uk1s3.embassy.ebi.ac.uk/deciphon/minifam.hmm.7z

      - name: Extract minifam.hmm
        run: 7z x minifam.hmm.7z

      - name: Damage minifam.hmm
        if: matrix.test_when == 'failing'
        run: sed -i 's/./xxx/2;s/./xxx/157;s/./xxx/106' minifam.hmm

      - name: Run h3daemon when working
        if: matrix.test_when == 'working'
        run: |
          loginctl enable-linger 1001
          ./h3daemon start minifam.hmm --yes

      - name: Run h3daemon when failing
        if: matrix.test_when == 'failing'
        run: |
          loginctl enable-linger 1001
          ./h3daemon start minifam.hmm --yes || exit 0
